#%RAML 1.0
title: Fonction A4 - Service REST
mediaType: application/json
types:
  Poursuite:
    properties:
      id:
        type: string
        required: true
      id_etablsmnt:
        type: string
        required: true
      nom:
        type: string
        required: true
      proprietaire:
        type: string
        required: true
      adresse:
        type: string
        required: true
      ville:
        type: string
        required: true
      statut:
        type: string
        required: true
      date_poursuite:
        type: string
        required: true
      date_jugement:
        type: string
        required: true
      description:
        type: string
        required: true
      montant: 
        type: number
        required: true
/api:
  /contrevenants:
    get:
      description: Avoir la liste des contravenants qui ont obtenu des contraventions entre 2 dates.
      parametre_requete: 
        du:
          type: text
          required: true
          description: Date de début pour la recherche (format: YYYY-MM-DD)
        au:
          type: text
          required: true
          description: Date de fin pour la recherche (format: YYYY-MM-DD) 
      responses:
        200:
          body:
            application/json:
              type: Poursuite[]
              example:
                [
                  {
                    "adresse": "2101 Av. Dollard, Local 33, LaSalle, Québec",
                    "date_jugement": "20221109",
                    "date_poursuite": "20220309",
                    "id": 8512,
                    "id_etablsmnt": 123679,
                    "montant": 500,
                    "motif": "Les personnes affectées à la préparation des produits, au lavage ou au nettoyage du matériel et de l'équipement doivent: porter un bonnet ou une résille propre qui recouvre entièrement les cheveux; porter un couvre-barbe propre qui recouvre entièrement la barbe.",
                    "nom_etablsmnt": "DEJEUNER MICKAEL",
                    "proprietaire": "9344-4131 QUEBEC INC.",
                    "statut": "Fermé",
                    "ville": "LaSalle"
                  }
                ]
        404:
          description: pas de contrevenants.
  /poursuites:
    get:
      description: Avoir la liste des poursuites qui ont été faites pour l'établissement en parametre.
      parametre_requete: 
        nom:
          type: text
          required: true
          description: Le nom de l'établissement pour lequel on veut afficher les poursuites qu'il a subi.
      responses:
        200:
          body:
            application/json:
              type: Poursuite[]
              example:
                [
                  {
                    "adresse": "2101 Av. Dollard, Local 33, LaSalle, Québec",
                    "date_jugement": "20221109",
                    "date_poursuite": "20220309",
                    "id": 8512,
                    "id_etablsmnt": 123679,
                    "montant": 500,
                    "motif": "Les personnes affectées à la préparation des produits, au lavage ou au nettoyage du matériel et de l'équipement doivent: porter un bonnet ou une résille propre qui recouvre entièrement les cheveux; porter un couvre-barbe propre qui recouvre entièrement la barbe.",
                    "nom_etablsmnt": "DEJEUNER MICKAEL",
                    "proprietaire": "9344-4131 QUEBEC INC.",
                    "statut": "Fermé",
                    "ville": "LaSalle"
                  }
                ]
        404:
          description: pas de poursuite.
  /nbr_infractions_etablissements:
    get:
      description: 
        Avoir la liste des établissements et le nombre de poursuites qu'ils ont eu. la liste retournée est ordonnée par ordre décroissant selon le nbr de poursuites.
      responses:
        200:
          body:
            application/json:
              type: []
              example:
                [
                  {
                    "nbr": 19,
                    "nom": "SUPER MARCHE TROPIC"
                  },
                  {
                    "nbr": 17,
                    "nom": "RESTAURANT JADE QUARTIER CHINOIS"
                  },
                  {
                    "nbr": 17,
                    "nom": "BUFFALO BILL WINGS"
                  }
                ]
        404:
          description: pas d'établissements.
        500:
          description: problème au niveau du serveur.